console.log(5 == 20 / 2);
console.log("usman".toString() === "usmAn".toString());
console.log("usman".toLowerCase() == "uSman".toLowerCase());
console.log(20 % 2 == 0 ? true : false);
var name = "daniyal";
console.log(name == "dani");
var age = 20;
console.log(100 / 5 == age);
var mobile = "my age is 20";
console.log(mobile.includes(String(20)));
var intro = "my Name is usman";
console.log(intro.toLowerCase().includes("usman".toLowerCase()));
console.log(5 == 1 / 2 && name === "daniyal");
console.log(age.toString() == mobile);
